name: nomadiq
description: "A Flutter app for exploring Kenyan tourist destinations."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_animate: ^4.2.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true



